// <auto-generated />
using System;
using CafeEmployeesDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeEmployeesDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910135503_SeedStaticData")]
    partial class SeedStaticData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeEmployeesDemo.Models.Cafe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Trendy cafe in the city center",
                            Location = "Downtown",
                            Logo = "https://example.com/downtown.png",
                            Name = "Downtown Cafe"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Relaxing cafe by the sea",
                            Location = "Beach",
                            Logo = "https://example.com/beach.png",
                            Name = "Beachside Cafe"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Student-friendly cafe near the university",
                            Location = "Campus",
                            Name = "Campus Cafe"
                        });
                });

            modelBuilder.Entity("CafeEmployeesDemo.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "UI123456A",
                            EmailAddress = "alice@example.com",
                            Gender = "Female",
                            Name = "Alice Tan",
                            PhoneNumber = "91234567"
                        },
                        new
                        {
                            Id = "UI234567B",
                            EmailAddress = "bob@example.com",
                            Gender = "Male",
                            Name = "Bob Lim",
                            PhoneNumber = "81234567"
                        },
                        new
                        {
                            Id = "UI345678C",
                            EmailAddress = "chloe@example.com",
                            Gender = "Female",
                            Name = "Chloe Ng",
                            PhoneNumber = "92345678"
                        },
                        new
                        {
                            Id = "UI456789D",
                            EmailAddress = "david@example.com",
                            Gender = "Male",
                            Name = "David Wong",
                            PhoneNumber = "83456789"
                        });
                });

            modelBuilder.Entity("CafeEmployeesDemo.Models.Employment", b =>
                {
                    b.Property<int>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentId"));

                    b.Property<Guid>("CafeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmploymentId");

                    b.HasIndex("CafeId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Employments");

                    b.HasData(
                        new
                        {
                            EmploymentId = -1,
                            CafeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeId = "UI123456A",
                            StartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmploymentId = -2,
                            CafeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeId = "UI234567B",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmploymentId = -3,
                            CafeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EmployeeId = "UI345678C",
                            StartDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CafeEmployeesDemo.Models.Employment", b =>
                {
                    b.HasOne("CafeEmployeesDemo.Models.Cafe", "Cafe")
                        .WithMany("Employees")
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeEmployeesDemo.Models.Employee", "Employee")
                        .WithOne("Employment")
                        .HasForeignKey("CafeEmployeesDemo.Models.Employment", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafe");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CafeEmployeesDemo.Models.Cafe", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CafeEmployeesDemo.Models.Employee", b =>
                {
                    b.Navigation("Employment");
                });
#pragma warning restore 612, 618
        }
    }
}
